import 'package:flutter/material.dart';

class CountryAndFlags {
  const CountryAndFlags({
    @required this.name,
    @required this.flag,
    @required this.code,
    @required this.dialCode,
  });

  final String name;
  final String flag;
  final String code;
  final String dialCode;

  static const List<CountryAndFlags> countries = [
    CountryAndFlags(
      name: "Afghanistan",
      flag: "🇦🇫",
      code: "AF",
      dialCode: "+93",
    ),
    CountryAndFlags(
      name: "Åland Islands",
      flag: "🇦🇽",
      code: "AX",
      dialCode: "+358",
    ),
    CountryAndFlags(
      name: "Albania",
      flag: "🇦🇱",
      code: "AL",
      dialCode: "+355",
    ),
    CountryAndFlags(
      name: "Algeria",
      flag: "🇩🇿",
      code: "DZ",
      dialCode: "+213",
    ),
    CountryAndFlags(
      name: "American Samoa",
      flag: "🇦🇸",
      code: "AS",
      dialCode: "+1684",
    ),
    CountryAndFlags(
      name: "Andorra",
      flag: "🇦🇩",
      code: "AD",
      dialCode: "+376",
    ),
    CountryAndFlags(
      name: "Angola",
      flag: "🇦🇴",
      code: "AO",
      dialCode: "+244",
    ),
    CountryAndFlags(
      name: "Anguilla",
      flag: "🇦🇮",
      code: "AI",
      dialCode: "+1264",
    ),
    CountryAndFlags(
      name: "Antarctica",
      flag: "🇦🇶",
      code: "AQ",
      dialCode: "+672",
    ),
    CountryAndFlags(
      name: "Antigua and Barbuda",
      flag: "🇦🇬",
      code: "AG",
      dialCode: "+1268",
    ),
    CountryAndFlags(
      name: "Argentina",
      flag: "🇦🇷",
      code: "AR",
      dialCode: "+54",
    ),
    CountryAndFlags(
      name: "Armenia",
      flag: "🇦🇲",
      code: "AM",
      dialCode: "+374",
    ),
    CountryAndFlags(
      name: "Aruba",
      flag: "🇦🇼",
      code: "AW",
      dialCode: "+297",
    ),
    CountryAndFlags(
      name: "Australia",
      flag: "🇦🇺",
      code: "AU",
      dialCode: "+61",
    ),
    CountryAndFlags(
      name: "Austria",
      flag: "🇦🇹",
      code: "AT",
      dialCode: "+43",
    ),
    CountryAndFlags(
      name: "Azerbaijan",
      flag: "🇦🇿",
      code: "AZ",
      dialCode: "+994",
    ),
    CountryAndFlags(
      name: "Bahamas",
      flag: "🇧🇸",
      code: "BS",
      dialCode: "+1242",
    ),
    CountryAndFlags(
      name: "Bahrain",
      flag: "🇧🇭",
      code: "BH",
      dialCode: "+973",
    ),
    CountryAndFlags(
      name: "Bangladesh",
      flag: "🇧🇩",
      code: "BD",
      dialCode: "+880",
    ),
    CountryAndFlags(
      name: "Barbados",
      flag: "🇧🇧",
      code: "BB",
      dialCode: "+1246",
    ),
    CountryAndFlags(
      name: "Belarus",
      flag: "🇧🇾",
      code: "BY",
      dialCode: "+375",
    ),
    CountryAndFlags(
      name: "Belgium",
      flag: "🇧🇪",
      code: "BE",
      dialCode: "+32",
    ),
    CountryAndFlags(
      name: "Belize",
      flag: "🇧🇿",
      code: "BZ",
      dialCode: "+501",
    ),
    CountryAndFlags(
      name: "Benin",
      flag: "🇧🇯",
      code: "BJ",
      dialCode: "+229",
    ),
    CountryAndFlags(
      name: "Bermuda",
      flag: "🇧🇲",
      code: "BM",
      dialCode: "+1441",
    ),
    CountryAndFlags(
      name: "Bhutan",
      flag: "🇧🇹",
      code: "BT",
      dialCode: "+975",
    ),
    CountryAndFlags(
      name: "Bolivia, Plurinational State of bolivia",
      flag: "🇧🇴",
      code: "BO",
      dialCode: "+591",
    ),
    CountryAndFlags(
      name: "Bosnia and Herzegovina",
      flag: "🇧🇦",
      code: "BA",
      dialCode: "+387",
    ),
    CountryAndFlags(
      name: "Botswana",
      flag: "🇧🇼",
      code: "BW",
      dialCode: "+267",
    ),
    CountryAndFlags(
      name: "Bouvet Island",
      flag: "🇧🇻",
      code: "BV",
      dialCode: "+47",
    ),
    CountryAndFlags(
      name: "Brazil",
      flag: "🇧🇷",
      code: "BR",
      dialCode: "+55",
    ),
    CountryAndFlags(
      name: "British Indian Ocean Territory",
      flag: "🇮🇴",
      code: "IO",
      dialCode: "+246",
    ),
    CountryAndFlags(
      name: "Brunei Darussalam",
      flag: "🇧🇳",
      code: "BN",
      dialCode: "+673",
    ),
    CountryAndFlags(
      name: "Bulgaria",
      flag: "🇧🇬",
      code: "BG",
      dialCode: "+359",
    ),
    CountryAndFlags(
      name: "Burkina Faso",
      flag: "🇧🇫",
      code: "BF",
      dialCode: "+226",
    ),
    CountryAndFlags(
      name: "Burundi",
      flag: "🇧🇮",
      code: "BI",
      dialCode: "+257",
    ),
    CountryAndFlags(
      name: "Cambodia",
      flag: "🇰🇭",
      code: "KH",
      dialCode: "+855",
    ),
    CountryAndFlags(
      name: "Cameroon",
      flag: "🇨🇲",
      code: "CM",
      dialCode: "+237",
    ),
    CountryAndFlags(
      name: "Canada",
      flag: "🇨🇦",
      code: "CA",
      dialCode: "+1",
    ),
    CountryAndFlags(
      name: "Cape Verde",
      flag: "🇨🇻",
      code: "CV",
      dialCode: "+238",
    ),
    CountryAndFlags(
      name: "Cayman Islands",
      flag: "🇰🇾",
      code: "KY",
      dialCode: "+345",
    ),
    CountryAndFlags(
      name: "Central African Republic",
      flag: "🇨🇫",
      code: "CF",
      dialCode: "+236",
    ),
    CountryAndFlags(
      name: "Chad",
      flag: "🇹🇩",
      code: "TD",
      dialCode: "+235",
    ),
    CountryAndFlags(
      name: "Chile",
      flag: "🇨🇱",
      code: "CL",
      dialCode: "+56",
    ),
    CountryAndFlags(
      name: "China",
      flag: "🇨🇳",
      code: "CN",
      dialCode: "+86",
    ),
    CountryAndFlags(
      name: "Christmas Island",
      flag: "🇨🇽",
      code: "CX",
      dialCode: "+61",
    ),
    CountryAndFlags(
      name: "Cocos (Keeling) Islands",
      flag: "🇨🇨",
      code: "CC",
      dialCode: "+61",
    ),
    CountryAndFlags(
      name: "Colombia",
      flag: "🇨🇴",
      code: "CO",
      dialCode: "+57",
    ),
    CountryAndFlags(
      name: "Comoros",
      flag: "🇰🇲",
      code: "KM",
      dialCode: "+269",
    ),
    CountryAndFlags(
      name: "Congo",
      flag: "🇨🇬",
      code: "CG",
      dialCode: "+242",
    ),
    CountryAndFlags(
      name: "Congo, The Democratic Republic of the Congo",
      flag: "🇨🇩",
      code: "CD",
      dialCode: "+243",
    ),
    CountryAndFlags(
      name: "Cook Islands",
      flag: "🇨🇰",
      code: "CK",
      dialCode: "+682",
    ),
    CountryAndFlags(
      name: "Costa Rica",
      flag: "🇨🇷",
      code: "CR",
      dialCode: "+506",
    ),
    CountryAndFlags(
      name: "Cote d'Ivoire",
      flag: "🇨🇮",
      code: "CI",
      dialCode: "+225",
    ),
    CountryAndFlags(
      name: "Croatia",
      flag: "🇭🇷",
      code: "HR",
      dialCode: "+385",
    ),
    CountryAndFlags(
      name: "Cuba",
      flag: "🇨🇺",
      code: "CU",
      dialCode: "+53",
    ),
    CountryAndFlags(
      name: "Cyprus",
      flag: "🇨🇾",
      code: "CY",
      dialCode: "+357",
    ),
    CountryAndFlags(
      name: "Czech Republic",
      flag: "🇨🇿",
      code: "CZ",
      dialCode: "+420",
    ),
    CountryAndFlags(
      name: "Denmark",
      flag: "🇩🇰",
      code: "DK",
      dialCode: "+45",
    ),
    CountryAndFlags(
      name: "Djibouti",
      flag: "🇩🇯",
      code: "DJ",
      dialCode: "+253",
    ),
    CountryAndFlags(
      name: "Dominica",
      flag: "🇩🇲",
      code: "DM",
      dialCode: "+1767",
    ),
    CountryAndFlags(
      name: "Dominican Republic",
      flag: "🇩🇴",
      code: "DO",
      dialCode: "+1849",
    ),
    CountryAndFlags(
      name: "Ecuador",
      flag: "🇪🇨",
      code: "EC",
      dialCode: "+593",
    ),
    CountryAndFlags(
      name: "Egypt",
      flag: "🇪🇬",
      code: "EG",
      dialCode: "+20",
    ),
    CountryAndFlags(
      name: "El Salvador",
      flag: "🇸🇻",
      code: "SV",
      dialCode: "+503",
    ),
    CountryAndFlags(
      name: "Equatorial Guinea",
      flag: "🇬🇶",
      code: "GQ",
      dialCode: "+240",
    ),
    CountryAndFlags(
      name: "Eritrea",
      flag: "🇪🇷",
      code: "ER",
      dialCode: "+291",
    ),
    CountryAndFlags(
      name: "Estonia",
      flag: "🇪🇪",
      code: "EE",
      dialCode: "+372",
    ),
    CountryAndFlags(
      name: "Ethiopia",
      flag: "🇪🇹",
      code: "ET",
      dialCode: "+251",
    ),
    CountryAndFlags(
      name: "Falkland Islands (Malvinas)",
      flag: "🇫🇰",
      code: "FK",
      dialCode: "+500",
    ),
    CountryAndFlags(
      name: "Faroe Islands",
      flag: "🇫🇴",
      code: "FO",
      dialCode: "+298",
    ),
    CountryAndFlags(
      name: "Fiji",
      flag: "🇫🇯",
      code: "FJ",
      dialCode: "+679",
    ),
    CountryAndFlags(
      name: "Finland",
      flag: "🇫🇮",
      code: "FI",
      dialCode: "+358",
    ),
    CountryAndFlags(
      name: "France",
      flag: "🇫🇷",
      code: "FR",
      dialCode: "+33",
    ),
    CountryAndFlags(
      name: "French Guiana",
      flag: "🇬🇫",
      code: "GF",
      dialCode: "+594",
    ),
    CountryAndFlags(
      name: "French Polynesia",
      flag: "🇵🇫",
      code: "PF",
      dialCode: "+689",
    ),
    CountryAndFlags(
      name: "French Southern Territories",
      flag: "🇹🇫",
      code: "TF",
      dialCode: "+262",
    ),
    CountryAndFlags(
      name: "Gabon",
      flag: "🇬🇦",
      code: "GA",
      dialCode: "+241",
    ),
    CountryAndFlags(
      name: "Gambia",
      flag: "🇬🇲",
      code: "GM",
      dialCode: "+220",
    ),
    CountryAndFlags(
      name: "Georgia",
      flag: "🇬🇪",
      code: "GE",
      dialCode: "+995",
    ),
    CountryAndFlags(
      name: "Germany",
      flag: "🇩🇪",
      code: "DE",
      dialCode: "+49",
    ),
    CountryAndFlags(
      name: "Ghana",
      flag: "🇬🇭",
      code: "GH",
      dialCode: "+233",
    ),
    CountryAndFlags(
      name: "Gibraltar",
      flag: "🇬🇮",
      code: "GI",
      dialCode: "+350",
    ),
    CountryAndFlags(
      name: "Greece",
      flag: "🇬🇷",
      code: "GR",
      dialCode: "+30",
    ),
    CountryAndFlags(
      name: "Greenland",
      flag: "🇬🇱",
      code: "GL",
      dialCode: "+299",
    ),
    CountryAndFlags(
      name: "Grenada",
      flag: "🇬🇩",
      code: "GD",
      dialCode: "+1473",
    ),
    CountryAndFlags(
      name: "Guadeloupe",
      flag: "🇬🇵",
      code: "GP",
      dialCode: "+590",
    ),
    CountryAndFlags(
      name: "Guam",
      flag: "🇬🇺",
      code: "GU",
      dialCode: "+1671",
    ),
    CountryAndFlags(
      name: "Guatemala",
      flag: "🇬🇹",
      code: "GT",
      dialCode: "+502",
    ),
    CountryAndFlags(
      name: "Guernsey",
      flag: "🇬🇬",
      code: "GG",
      dialCode: "+44",
    ),
    CountryAndFlags(
      name: "Guinea",
      flag: "🇬🇳",
      code: "GN",
      dialCode: "+224",
    ),
    CountryAndFlags(
      name: "Guinea-Bissau",
      flag: "🇬🇼",
      code: "GW",
      dialCode: "+245",
    ),
    CountryAndFlags(
      name: "Guyana",
      flag: "🇬🇾",
      code: "GY",
      dialCode: "+592",
    ),
    CountryAndFlags(
      name: "Haiti",
      flag: "🇭🇹",
      code: "HT",
      dialCode: "+509",
    ),
    CountryAndFlags(
      name: "Heard Island and Mcdonald Islands",
      flag: "🇭🇲",
      code: "HM",
      dialCode: "+672",
    ),
    CountryAndFlags(
      name: "Holy See (Vatican City State)",
      flag: "🇻🇦",
      code: "VA",
      dialCode: "+379",
    ),
    CountryAndFlags(
      name: "Honduras",
      flag: "🇭🇳",
      code: "HN",
      dialCode: "+504",
    ),
    CountryAndFlags(
      name: "Hong Kong",
      flag: "🇭🇰",
      code: "HK",
      dialCode: "+852",
    ),
    CountryAndFlags(
      name: "Hungary",
      flag: "🇭🇺",
      code: "HU",
      dialCode: "+36",
    ),
    CountryAndFlags(
      name: "Iceland",
      flag: "🇮🇸",
      code: "IS",
      dialCode: "+354",
    ),
    CountryAndFlags(
      name: "India",
      flag: "🇮🇳",
      code: "IN",
      dialCode: "+91",
    ),
    CountryAndFlags(
      name: "Indonesia",
      flag: "🇮🇩",
      code: "ID",
      dialCode: "+62",
    ),
    CountryAndFlags(
      name: "Iran, Islamic Republic of Persian Gulf",
      flag: "🇮🇷",
      code: "IR",
      dialCode: "+98",
    ),
    CountryAndFlags(
      name: "Iraq",
      flag: "🇮🇶",
      code: "IQ",
      dialCode: "+964",
    ),
    CountryAndFlags(
      name: "Ireland",
      flag: "🇮🇪",
      code: "IE",
      dialCode: "+353",
    ),
    CountryAndFlags(
      name: "Isle of Man",
      flag: "🇮🇲",
      code: "IM",
      dialCode: "+44",
    ),
    CountryAndFlags(
      name: "Israel",
      flag: "🇮🇱",
      code: "IL",
      dialCode: "+972",
    ),
    CountryAndFlags(
      name: "Italy",
      flag: "🇮🇹",
      code: "IT",
      dialCode: "+39",
    ),
    CountryAndFlags(
      name: "Jamaica",
      flag: "🇯🇲",
      code: "JM",
      dialCode: "+1876",
    ),
    CountryAndFlags(
      name: "Japan",
      flag: "🇯🇵",
      code: "JP",
      dialCode: "+81",
    ),
    CountryAndFlags(
      name: "Jersey",
      flag: "🇯🇪",
      code: "JE",
      dialCode: "+44",
    ),
    CountryAndFlags(
      name: "Jordan",
      flag: "🇯🇴",
      code: "JO",
      dialCode: "+962",
    ),
    CountryAndFlags(
      name: "Kazakhstan",
      flag: "🇰🇿",
      code: "KZ",
      dialCode: "+7",
    ),
    CountryAndFlags(
      name: "Kenya",
      flag: "🇰🇪",
      code: "KE",
      dialCode: "+254",
    ),
    CountryAndFlags(
      name: "Kiribati",
      flag: "🇰🇮",
      code: "KI",
      dialCode: "+686",
    ),
    CountryAndFlags(
      name: "Korea, Democratic People's Republic of Korea",
      flag: "🇰🇵",
      code: "KP",
      dialCode: "+850",
    ),
    CountryAndFlags(
      name: "Korea, Republic of South Korea",
      flag: "🇰🇷",
      code: "KR",
      dialCode: "+82",
    ),
    CountryAndFlags(
      name: "Kosovo",
      flag: "🇽🇰",
      code: "XK",
      dialCode: "+383",
    ),
    CountryAndFlags(
      name: "Kuwait",
      flag: "🇰🇼",
      code: "KW",
      dialCode: "+965",
    ),
    CountryAndFlags(
      name: "Kyrgyzstan",
      flag: "🇰🇬",
      code: "KG",
      dialCode: "+996",
    ),
    CountryAndFlags(
      name: "Laos",
      flag: "🇱🇦",
      code: "LA",
      dialCode: "+856",
    ),
    CountryAndFlags(
      name: "Latvia",
      flag: "🇱🇻",
      code: "LV",
      dialCode: "+371",
    ),
    CountryAndFlags(
      name: "Lebanon",
      flag: "🇱🇧",
      code: "LB",
      dialCode: "+961",
    ),
    CountryAndFlags(
      name: "Lesotho",
      flag: "🇱🇸",
      code: "LS",
      dialCode: "+266",
    ),
    CountryAndFlags(
      name: "Liberia",
      flag: "🇱🇷",
      code: "LR",
      dialCode: "+231",
    ),
    CountryAndFlags(
      name: "Libyan Arab Jamahiriya",
      flag: "🇱🇾",
      code: "LY",
      dialCode: "+218",
    ),
    CountryAndFlags(
      name: "Liechtenstein",
      flag: "🇱🇮",
      code: "LI",
      dialCode: "+423",
    ),
    CountryAndFlags(
      name: "Lithuania",
      flag: "🇱🇹",
      code: "LT",
      dialCode: "+370",
    ),
    CountryAndFlags(
      name: "Luxembourg",
      flag: "🇱🇺",
      code: "LU",
      dialCode: "+352",
    ),
    CountryAndFlags(
      name: "Macao",
      flag: "🇲🇴",
      code: "MO",
      dialCode: "+853",
    ),
    CountryAndFlags(
        name: "Macedonia", flag: "🇲🇰", code: "MK", dialCode: "+389"),
    CountryAndFlags(
      name: "Madagascar",
      flag: "🇲🇬",
      code: "MG",
      dialCode: "+261",
    ),
    CountryAndFlags(
      name: "Malawi",
      flag: "🇲🇼",
      code: "MW",
      dialCode: "+265",
    ),
    CountryAndFlags(
      name: "Malaysia",
      flag: "🇲🇾",
      code: "MY",
      dialCode: "+60",
    ),
    CountryAndFlags(
      name: "Maldives",
      flag: "🇲🇻",
      code: "MV",
      dialCode: "+960",
    ),
    CountryAndFlags(name: "Mali", flag: "🇲🇱", code: "ML", dialCode: "+223"),
    CountryAndFlags(
      name: "Malta",
      flag: "🇲🇹",
      code: "MT",
      dialCode: "+356",
    ),
    CountryAndFlags(
      name: "Marshall Islands",
      flag: "🇲🇭",
      code: "MH",
      dialCode: "+692",
    ),
    CountryAndFlags(
      name: "Martinique",
      flag: "🇲🇶",
      code: "MQ",
      dialCode: "+596",
    ),
    CountryAndFlags(
      name: "Mauritania",
      flag: "🇲🇷",
      code: "MR",
      dialCode: "+222",
    ),
    CountryAndFlags(
      name: "Mauritius",
      flag: "🇲🇺",
      code: "MU",
      dialCode: "+230",
    ),
    CountryAndFlags(
      name: "Mayotte",
      flag: "🇾🇹",
      code: "YT",
      dialCode: "+262",
    ),
    CountryAndFlags(
      name: "Mexico",
      flag: "🇲🇽",
      code: "MX",
      dialCode: "+52",
    ),
    CountryAndFlags(
      name: "Micronesia, Federated States of Micronesia",
      flag: "🇫🇲",
      code: "FM",
      dialCode: "+691",
    ),
    CountryAndFlags(
      name: "Moldova",
      flag: "🇲🇩",
      code: "MD",
      dialCode: "+373",
    ),
    CountryAndFlags(
      name: "Monaco",
      flag: "🇲🇨",
      code: "MC",
      dialCode: "+377",
    ),
    CountryAndFlags(
      name: "Mongolia",
      flag: "🇲🇳",
      code: "MN",
      dialCode: "+976",
    ),
    CountryAndFlags(
      name: "Montenegro",
      flag: "🇲🇪",
      code: "ME",
      dialCode: "+382",
    ),
    CountryAndFlags(
      name: "Montserrat",
      flag: "🇲🇸",
      code: "MS",
      dialCode: "+1664",
    ),
    CountryAndFlags(
      name: "Morocco",
      flag: "🇲🇦",
      code: "MA",
      dialCode: "+212",
    ),
    CountryAndFlags(
      name: "Mozambique",
      flag: "🇲🇿",
      code: "MZ",
      dialCode: "+258",
    ),
    CountryAndFlags(
      name: "Myanmar",
      flag: "🇲🇲",
      code: "MM",
      dialCode: "+95",
    ),
    CountryAndFlags(
      name: "Namibia",
      flag: "🇳🇦",
      code: "NA",
      dialCode: "+264",
    ),
    CountryAndFlags(
      name: "Nauru",
      flag: "🇳🇷",
      code: "NR",
      dialCode: "+674",
    ),
    CountryAndFlags(
      name: "Nepal",
      flag: "🇳🇵",
      code: "NP",
      dialCode: "+977",
    ),
    CountryAndFlags(
      name: "Netherlands",
      flag: "🇳🇱",
      code: "NL",
      dialCode: "+31",
    ),
    CountryAndFlags(
      name: "Netherlands Antilles",
      flag: "🇧🇶",
      code: "AN",
      dialCode: "+599",
    ),
    CountryAndFlags(
      name: "New Caledonia",
      flag: "🇳🇨",
      code: "NC",
      dialCode: "+687",
    ),
    CountryAndFlags(
      name: "New Zealand",
      flag: "🇳🇿",
      code: "NZ",
      dialCode: "+64",
    ),
    CountryAndFlags(
      name: "Nicaragua",
      flag: "🇳🇮",
      code: "NI",
      dialCode: "+505",
    ),
    CountryAndFlags(
      name: "Niger",
      flag: "🇳🇪",
      code: "NE",
      dialCode: "+227",
    ),
    CountryAndFlags(
      name: "Nigeria",
      flag: "🇳🇬",
      code: "NG",
      dialCode: "+234",
    ),
    CountryAndFlags(
      name: "Niue",
      flag: "🇳🇺",
      code: "NU",
      dialCode: "+683",
    ),
    CountryAndFlags(
      name: "Norfolk Island",
      flag: "🇳🇫",
      code: "NF",
      dialCode: "+672",
    ),
    CountryAndFlags(
      name: "Northern Mariana Islands",
      flag: "🇲🇵",
      code: "MP",
      dialCode: "+1670",
    ),
    CountryAndFlags(
      name: "Norway",
      flag: "🇳🇴",
      code: "NO",
      dialCode: "+47",
    ),
    CountryAndFlags(
      name: "Oman",
      flag: "🇴🇲",
      code: "OM",
      dialCode: "+968",
    ),
    CountryAndFlags(
      name: "Pakistan",
      flag: "🇵🇰",
      code: "PK",
      dialCode: "+92",
    ),
    CountryAndFlags(
      name: "Palau",
      flag: "🇵🇼",
      code: "PW",
      dialCode: "+680",
    ),
    CountryAndFlags(
      name: "Palestinian Territory, Occupied",
      flag: "🇵🇸",
      code: "PS",
      dialCode: "+970",
    ),
    CountryAndFlags(
      name: "Panama",
      flag: "🇵🇦",
      code: "PA",
      dialCode: "+507",
    ),
    CountryAndFlags(
      name: "Papua New Guinea",
      flag: "🇵🇬",
      code: "PG",
      dialCode: "+675",
    ),
    CountryAndFlags(
      name: "Paraguay",
      flag: "🇵🇾",
      code: "PY",
      dialCode: "+595",
    ),
    CountryAndFlags(
      name: "Peru",
      flag: "🇵🇪",
      code: "PE",
      dialCode: "+51",
    ),
    CountryAndFlags(
      name: "Philippines",
      flag: "🇵🇭",
      code: "PH",
      dialCode: "+63",
    ),
    CountryAndFlags(
      name: "Pitcairn",
      flag: "🇵🇳",
      code: "PN",
      dialCode: "+64",
    ),
    CountryAndFlags(
      name: "Poland",
      flag: "🇵🇱",
      code: "PL",
      dialCode: "+48",
    ),
    CountryAndFlags(
      name: "Portugal",
      flag: "🇵🇹",
      code: "PT",
      dialCode: "+351",
    ),
    CountryAndFlags(
      name: "Puerto Rico",
      flag: "🇵🇷",
      code: "PR",
      dialCode: "+1939",
    ),
    CountryAndFlags(
      name: "Qatar",
      flag: "🇶🇦",
      code: "QA",
      dialCode: "+974",
    ),
    CountryAndFlags(
      name: "Romania",
      flag: "🇷🇴",
      code: "RO",
      dialCode: "+40",
    ),
    CountryAndFlags(
      name: "Russia",
      flag: "🇷🇺",
      code: "RU",
      dialCode: "+7",
    ),
    CountryAndFlags(
      name: "Rwanda",
      flag: "🇷🇼",
      code: "RW",
      dialCode: "+250",
    ),
    CountryAndFlags(
      name: "Reunion",
      flag: "🇷🇪",
      code: "RE",
      dialCode: "+262",
    ),
    CountryAndFlags(
      name: "Saint Barthelemy",
      flag: "🇧🇱",
      code: "BL",
      dialCode: "+590",
    ),
    CountryAndFlags(
      name: "Saint Helena, Ascension and Tristan Da Cunha",
      flag: "🇸🇭",
      code: "SH",
      dialCode: "+290",
    ),
    CountryAndFlags(
      name: "Saint Kitts and Nevis",
      flag: "🇰🇳",
      code: "KN",
      dialCode: "+1869",
    ),
    CountryAndFlags(
      name: "Saint Lucia",
      flag: "🇱🇨",
      code: "LC",
      dialCode: "+1758",
    ),
    CountryAndFlags(
      name: "Saint Martin",
      flag: "🇲🇫",
      code: "MF",
      dialCode: "+590",
    ),
    CountryAndFlags(
      name: "Saint Pierre and Miquelon",
      flag: "🇵🇲",
      code: "PM",
      dialCode: "+508",
    ),
    CountryAndFlags(
      name: "Saint Vincent and the Grenadines",
      flag: "🇻🇨",
      code: "VC",
      dialCode: "+1784",
    ),
    CountryAndFlags(
      name: "Samoa",
      flag: "🇼🇸",
      code: "WS",
      dialCode: "+685",
    ),
    CountryAndFlags(
      name: "San Marino",
      flag: "🇸🇲",
      code: "SM",
      dialCode: "+378",
    ),
    CountryAndFlags(
      name: "Sao Tome and Principe",
      flag: "🇸🇹",
      code: "ST",
      dialCode: "+239",
    ),
    CountryAndFlags(
      name: "Saudi Arabia",
      flag: "🇸🇦",
      code: "SA",
      dialCode: "+966",
    ),
    CountryAndFlags(
      name: "Senegal",
      flag: "🇸🇳",
      code: "SN",
      dialCode: "+221",
    ),
    CountryAndFlags(
      name: "Serbia",
      flag: "🇷🇸",
      code: "RS",
      dialCode: "+381",
    ),
    CountryAndFlags(
      name: "Seychelles",
      flag: "🇸🇨",
      code: "SC",
      dialCode: "+248",
    ),
    CountryAndFlags(
      name: "Sierra Leone",
      flag: "🇸🇱",
      code: "SL",
      dialCode: "+232",
    ),
    CountryAndFlags(
      name: "Singapore",
      flag: "🇸🇬",
      code: "SG",
      dialCode: "+65",
    ),
    CountryAndFlags(
      name: "Slovakia",
      flag: "🇸🇰",
      code: "SK",
      dialCode: "+421",
    ),
    CountryAndFlags(
      name: "Slovenia",
      flag: "🇸🇮",
      code: "SI",
      dialCode: "+386",
    ),
    CountryAndFlags(
      name: "Solomon Islands",
      flag: "🇸🇧",
      code: "SB",
      dialCode: "+677",
    ),
    CountryAndFlags(
      name: "Somalia",
      flag: "🇸🇴",
      code: "SO",
      dialCode: "+252",
    ),
    CountryAndFlags(
      name: "South Africa",
      flag: "🇿🇦",
      code: "ZA",
      dialCode: "+27",
    ),
    CountryAndFlags(
      name: "South Sudan",
      flag: "🇸🇸",
      code: "SS",
      dialCode: "+211",
    ),
    CountryAndFlags(
      name: "South Georgia and the South Sandwich Islands",
      flag: "🇬🇸",
      code: "GS",
      dialCode: "+500",
    ),
    CountryAndFlags(
      name: "Spain",
      flag: "🇪🇸",
      code: "ES",
      dialCode: "+34",
    ),
    CountryAndFlags(
      name: "Sri Lanka",
      flag: "🇱🇰",
      code: "LK",
      dialCode: "+94",
    ),
    CountryAndFlags(
      name: "Sudan",
      flag: "🇸🇩",
      code: "SD",
      dialCode: "+249",
    ),
    CountryAndFlags(
      name: "Suriname",
      flag: "🇸🇷",
      code: "SR",
      dialCode: "+597",
    ),
    CountryAndFlags(
      name: "Svalbard and Jan Mayen",
      flag: "🇸🇯",
      code: "SJ",
      dialCode: "+47",
    ),
    CountryAndFlags(
      name: "Swaziland",
      flag: "🇸🇿",
      code: "SZ",
      dialCode: "+268",
    ),
    CountryAndFlags(
      name: "Sweden",
      flag: "🇸🇪",
      code: "SE",
      dialCode: "+46",
    ),
    CountryAndFlags(
      name: "Switzerland",
      flag: "🇨🇭",
      code: "CH",
      dialCode: "+41",
    ),
    CountryAndFlags(
      name: "Syrian Arab Republic",
      flag: "🇸🇾",
      code: "SY",
      dialCode: "+963",
    ),
    CountryAndFlags(
      name: "Taiwan",
      flag: "🇹🇼",
      code: "TW",
      dialCode: "+886",
    ),
    CountryAndFlags(
      name: "Tajikistan",
      flag: "🇹🇯",
      code: "TJ",
      dialCode: "+992",
    ),
    CountryAndFlags(
      name: "Tanzania, United Republic of Tanzania",
      flag: "🇹🇿",
      code: "TZ",
      dialCode: "+255",
    ),
    CountryAndFlags(
      name: "Thailand",
      flag: "🇹🇭",
      code: "TH",
      dialCode: "+66",
    ),
    CountryAndFlags(
      name: "Timor-Leste",
      flag: "🇹🇱",
      code: "TL",
      dialCode: "+670",
    ),
    CountryAndFlags(
      name: "Togo",
      flag: "🇹🇬",
      code: "TG",
      dialCode: "+228",
    ),
    CountryAndFlags(
      name: "Tokelau",
      flag: "🇹🇰",
      code: "TK",
      dialCode: "+690",
    ),
    CountryAndFlags(
      name: "Tonga",
      flag: "🇹🇴",
      code: "TO",
      dialCode: "+676",
    ),
    CountryAndFlags(
      name: "Trinidad and Tobago",
      flag: "🇹🇹",
      code: "TT",
      dialCode: "+1868",
    ),
    CountryAndFlags(
      name: "Tunisia",
      flag: "🇹🇳",
      code: "TN",
      dialCode: "+216",
    ),
    CountryAndFlags(
      name: "Turkey",
      flag: "🇹🇷",
      code: "TR",
      dialCode: "+90",
    ),
    CountryAndFlags(
      name: "Turkmenistan",
      flag: "🇹🇲",
      code: "TM",
      dialCode: "+993",
    ),
    CountryAndFlags(
      name: "Turks and Caicos Islands",
      flag: "🇹🇨",
      code: "TC",
      dialCode: "+1649",
    ),
    CountryAndFlags(
      name: "Tuvalu",
      flag: "🇹🇻",
      code: "TV",
      dialCode: "+688",
    ),
    CountryAndFlags(
      name: "Uganda",
      flag: "🇺🇬",
      code: "UG",
      dialCode: "+256",
    ),
    CountryAndFlags(
      name: "Ukraine",
      flag: "🇺🇦",
      code: "UA",
      dialCode: "+380",
    ),
    CountryAndFlags(
      name: "United Arab Emirates",
      flag: "🇦🇪",
      code: "AE",
      dialCode: "+971",
    ),
    CountryAndFlags(
      name: "United Kingdom",
      flag: "🇬🇧",
      code: "GB",
      dialCode: "+44",
    ),
    CountryAndFlags(
      name: "United States",
      flag: "🇺🇸",
      code: "US",
      dialCode: "+1",
    ),
    CountryAndFlags(
      name: "Uruguay",
      flag: "🇺🇾",
      code: "UY",
      dialCode: "+598",
    ),
    CountryAndFlags(
      name: "Uzbekistan",
      flag: "🇺🇿",
      code: "UZ",
      dialCode: "+998",
    ),
    CountryAndFlags(
      name: "Vanuatu",
      flag: "🇻🇺",
      code: "VU",
      dialCode: "+678",
    ),
    CountryAndFlags(
      name: "Venezuela, Bolivarian Republic of Venezuela",
      flag: "🇻🇪",
      code: "VE",
      dialCode: "+58",
    ),
    CountryAndFlags(
      name: "Vietnam",
      flag: "🇻🇳",
      code: "VN",
      dialCode: "+84",
    ),
    CountryAndFlags(
      name: "Virgin Islands, British",
      flag: "🇻🇬",
      code: "VG",
      dialCode: "+1284",
    ),
    CountryAndFlags(
      name: "Virgin Islands, U.S.",
      flag: "🇻🇮",
      code: "VI",
      dialCode: "+1340",
    ),
    CountryAndFlags(
      name: "Wallis and Futuna",
      flag: "🇼🇫",
      code: "WF",
      dialCode: "+681",
    ),
    CountryAndFlags(
      name: "Yemen",
      flag: "🇾🇪",
      code: "YE",
      dialCode: "+967",
    ),
    CountryAndFlags(
      name: "Zambia",
      flag: "🇿🇲",
      code: "ZM",
      dialCode: "+260",
    ),
    CountryAndFlags(
      name: "Zimbabwe",
      flag: "🇿🇼",
      code: "ZW",
      dialCode: "+263",
    )
  ];
}
